name: Generate Doxygen Documentation

on:

  workflow_run:

    workflows: ["Compile & Run Example"]

    types:
      - completed

jobs:
  doxygen:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update & Upgrade ubuntu
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y

      - name: Install Doxygen
        run: sudo apt install -y doxygen

      - name: Verify Doxygen installation
        run: doxygen --version

      - name: Install Graphviz 
        run: sudo apt install -y graphviz

      - name: Verify Graphviz installation
        run: dot -V

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: html
          if-no-files-found: error

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push'  &&  github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html

