name: Generate Doxygen Documentation

on:

  workflow_run:

    workflows: ["Compile & Run Example"]

    types:
      - completed

concurrency:

  group: "pages"

  cancel-in-progress: false

permissions:
  contents: write

jobs:

  doxygen:

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt install -y doxygen

      - name: Verify Doxygen installation
        run: doxygen --version

      - name: Install Graphviz 
        run: sudo apt install -y graphviz

      - name: Verify Graphviz installation
        run: dot -V

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: html
          if-no-files-found: error

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          publish_branch: gh-pages

