name: Compile & Run Example

on: [push, pull_request]

jobs:

  compile_and_run_example:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update & Upgrade ubuntu
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y

      - name: Verify gcc installation
        run: gcc --version

      - name: Install MPFI
        run: sudo apt-get install -y libmpfi-dev

      - name: Compile Example
        run: gcc example.c -Wall -Wextra -lgmp -lmpfr -lmpfi

      - name: Run Example
        run: ./a.out
